{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "cda2c589",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Hassan joined chatroom 'Python Lounge'\n",
      "Safwan joined chatroom 'Python Lounge'\n",
      "1: Hi (sent by Hassan)\n",
      "2: Hello (sent by Safwan)\n",
      "\n",
      "--- Chat History (Python Lounge) ---\n",
      "1: Hi (sent by Hassan)\n",
      "2: Hello (sent by Safwan)\n",
      "Safwan left chatroom 'Python Lounge'\n"
     ]
    }
   ],
   "source": [
    "# Message Class\n",
    "# Represents a single chat message\n",
    "\n",
    "class Message:\n",
    "    # Shared counter for all messages\n",
    "    message_counter = 1\n",
    "\n",
    "    def __init__(self, sender, content):\n",
    "        self.sender = sender          # User object who sent the message\n",
    "        self.content = content        # Message text\n",
    "\n",
    "        # Assign unique ID to the message\n",
    "        self.id = Message.message_counter\n",
    "        Message.message_counter += 1\n",
    "\n",
    "    def __str__(self):\n",
    "        return f\"{self.id}: {self.content} (sent by {self.sender.name})\"\n",
    "\n",
    "\n",
    "# User Class\n",
    "# Represents a chatroom user\n",
    "\n",
    "class User:\n",
    "\n",
    "    def __init__(self, name):\n",
    "        self.name = name\n",
    "        self.chatroom = None\n",
    "\n",
    "    # Join a chatroom\n",
    "    def join_chatroom(self, chatroom):\n",
    "\n",
    "        if self.chatroom:\n",
    "            print(f\"{self.name} is already in chatroom '{self.chatroom.name}'\")\n",
    "\n",
    "        else:\n",
    "            chatroom.add_user(self)\n",
    "            self.chatroom = chatroom\n",
    "\n",
    "            print(f\"{self.name} joined chatroom '{chatroom.name}'\")\n",
    "\n",
    "    # Leave current chatroom\n",
    "    def leave_chatroom(self):\n",
    "\n",
    "        if not self.chatroom:\n",
    "            print(f\"{self.name} is not in any chatroom\")\n",
    "\n",
    "        else:\n",
    "            room_name = self.chatroom.name\n",
    "\n",
    "            self.chatroom.remove_user(self)\n",
    "            self.chatroom = None\n",
    "\n",
    "            print(f\"{self.name} left chatroom '{room_name}'\")\n",
    "\n",
    "    # Send a message\n",
    "    def send_message(self, content):\n",
    "\n",
    "        if not self.chatroom:\n",
    "            print(f\"{self.name} cannot send messages because they are not in a chatroom\")\n",
    "\n",
    "        else:\n",
    "            self.chatroom.broadcast(self, content)\n",
    "\n",
    "\n",
    "# -------------------------------\n",
    "# Chatroom Class\n",
    "# Manages users and messages\n",
    "# -------------------------------\n",
    "\n",
    "class Chatroom:\n",
    "\n",
    "    def __init__(self, name):\n",
    "        self.name = name\n",
    "        self.users = []\n",
    "        self.messages = []\n",
    "\n",
    "    # Add user to room\n",
    "    def add_user(self, user):\n",
    "        self.users.append(user)\n",
    "\n",
    "    # Remove user from room\n",
    "    def remove_user(self, user):\n",
    "        self.users.remove(user)\n",
    "\n",
    "    # Create and store a new message\n",
    "    def broadcast(self, sender, content):\n",
    "\n",
    "        message = Message(sender, content)\n",
    "\n",
    "        self.messages.append(message)\n",
    "\n",
    "        print(message)\n",
    "\n",
    "    # Display all messages\n",
    "    def show_history(self):\n",
    "\n",
    "        print(f\"\\n--- Chat History ({self.name}) ---\")\n",
    "\n",
    "        for message in self.messages:\n",
    "            print(message)\n",
    "\n",
    "\n",
    "# Testing\n",
    "\n",
    "room = Chatroom(\"Python Lounge\")\n",
    "\n",
    "u1 = User(\"Hassan\")\n",
    "u2 = User(\"Safwan\")\n",
    "\n",
    "u1.join_chatroom(room)\n",
    "u2.join_chatroom(room)\n",
    "\n",
    "u1.send_message(\"Hi\")\n",
    "u2.send_message(\"Hello\")\n",
    "\n",
    "room.show_history()\n",
    "\n",
    "u2.leave_chatroom()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "546976a4",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
